#https://pypi.org/project/pcf8574-io/
import pcf8574_io
import Mock.GPIO as GPIO
import time

GPIO.setwarnings(False)

A = pcf8574_io.PCF(0x20)
A.pin_mode("A1", "INPUT")
A.pin_mode("A2", "INPUT")
A.pin_mode("A3", "INPUT")
A.pin_mode("A4", "INPUT")
A.pin_mode("A5", "INPUT")
A.pin_mode("A6", "INPUT")
A.pin_mode("A7", "INPUT")
A.pin_mode("A8", "INPUT")
B = pcf8574_io.PCF(0x21)
B.pin_mode("B1", "INPUT")
B.pin_mode("B2", "INPUT")
B.pin_mode("B3", "INPUT")
B.pin_mode("B4", "INPUT")
B.pin_mode("B5", "INPUT")
B.pin_mode("B6", "INPUT")
B.pin_mode("B7", "INPUT")
B.pin_mode("B8", "INPUT")
C = pcf8574_io.PCF(0x22)
C.pin_mode("C1", "INPUT")
C.pin_mode("C2", "INPUT")
C.pin_mode("C3", "INPUT")
C.pin_mode("C4", "INPUT")
C.pin_mode("C5", "INPUT")
C.pin_mode("C6", "INPUT")
C.pin_mode("C7", "INPUT")
C.pin_mode("C8", "INPUT")
D = pcf8574_io.PCF(0x23)
D.pin_mode("D1", "INPUT")
D.pin_mode("D2", "INPUT")
D.pin_mode("D3", "INPUT")
D.pin_mode("D4", "INPUT")
D.pin_mode("D5", "INPUT")
D.pin_mode("D6", "INPUT")
D.pin_mode("D7", "INPUT")
D.pin_mode("D8", "INPUT")
E = pcf8574_io.PCF(0x24)
E.pin_mode("E1", "INPUT")
E.pin_mode("E2", "INPUT")
E.pin_mode("E3", "INPUT")
E.pin_mode("E4", "INPUT")
E.pin_mode("E5", "INPUT")
E.pin_mode("E6", "INPUT")
E.pin_mode("E7", "INPUT")
E.pin_mode("E8", "INPUT")
def getIR():
    
    return();
