#https://pypi.org/project/pcf8574-io/
import pcf8574_io
import Mock.GPIO as GPIO
import time

GPIO.setwarnings(False)

p1 = pcf8574_io.PCF(0x20)
p1.pin_mode("p0", "INPUT")
p1.pin_mode("p1", "INPUT")
p1.pin_mode("p2", "INPUT")
p1.pin_mode("p3", "INPUT")
p1.pin_mode("p4", "INPUT")
p1.pin_mode("p5", "INPUT")
p1.pin_mode("p6", "INPUT")
p1.pin_mode("p7", "INPUT")
p2 = pcf8574_io.PCF(0x21)
p2.pin_mode("p0", "INPUT")
p2.pin_mode("p1", "INPUT")
p2.pin_mode("p2", "INPUT")
p2.pin_mode("p3", "INPUT")
p2.pin_mode("p4", "INPUT")
p2.pin_mode("p5", "INPUT")
p2.pin_mode("p6", "INPUT")
p2.pin_mode("p7", "INPUT")
p3 = pcf8574_io.PCF(0x22)
p3.pin_mode("p0", "INPUT")
p3.pin_mode("p1", "INPUT")
p3.pin_mode("p2", "INPUT")
p3.pin_mode("p3", "INPUT")
p3.pin_mode("p4", "INPUT")
p3.pin_mode("p5", "INPUT")
p3.pin_mode("p6", "INPUT")
p3.pin_mode("p7", "INPUT")
p4 = pcf8574_io.PCF(0x23)
p4.pin_mode("p0", "INPUT")
p4.pin_mode("p1", "INPUT")
p4.pin_mode("p2", "INPUT")
p4.pin_mode("p3", "INPUT")
p4.pin_mode("p4", "INPUT")
p4.pin_mode("p5", "INPUT")
p4.pin_mode("p6", "INPUT")
p4.pin_mode("p7", "INPUT")
p5 = pcf8574_io.PCF(0x24)
p5.pin_mode("p0", "INPUT")
p5.pin_mode("p1", "INPUT")
p5.pin_mode("p2", "INPUT")
p5.pin_mode("p3", "INPUT")
p5.pin_mode("p4", "INPUT")
p5.pin_mode("p5", "INPUT")
p5.pin_mode("p6", "INPUT")
p5.pin_mode("p7", "INPUT")